# Generated by Django 3.1.5 on 2021-01-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='velomarsh',
            name='marsh_image',
            field=models.FileField(upload_to='marsh_images/'),
        ),
    ]
