# Generated by Django 3.1.5 on 2021-01-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0002_auto_20210126_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='velomarsh',
            name='marsh_image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
