# Generated by Django 3.1.5 on 2021-01-31 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0003_auto_20210127_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryMarsh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_marsh_name', models.CharField(max_length=100)),
                ('history_marsh_image', models.FileField(upload_to='images/')),
                ('history_marsh_text', models.CharField(max_length=300)),
                ('history_marsh_km', models.CharField(max_length=300)),
                ('history_marsh_time', models.CharField(max_length=30)),
                ('history_marsh_obj', models.CharField(max_length=300)),
            ],
        ),
    ]
