# Generated by Django 3.1.5 on 2021-01-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0004_historymarsh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historymarsh',
            name='history_marsh_text',
            field=models.TextField(),
        ),
    ]
