# Generated by Django 3.1.5 on 2021-02-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0005_auto_20210131_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quetion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_text', models.CharField(max_length=300)),
                ('que_text_raz', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='WarMarsh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('war_marsh_name', models.CharField(max_length=100)),
                ('war_marsh_image', models.FileField(upload_to='images/')),
                ('war_marsh_text', models.TextField()),
                ('war_marsh_km', models.CharField(max_length=300)),
                ('war_marsh_time', models.CharField(max_length=30)),
                ('war_marsh_obj', models.CharField(max_length=300)),
            ],
        ),
    ]
