# Generated by Django 3.1.5 on 2021-02-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0006_quetion_warmarsh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historymarsh',
            name='history_marsh_image',
        ),
        migrations.AddField(
            model_name='historymarsh',
            name='history_marsh_url_1',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historymarsh',
            name='history_marsh_url_2',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
