# Generated by Django 3.1.5 on 2021-02-03 07:55

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0007_auto_20210202_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='velo.velomarsh', verbose_name='Категория')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='velo.category', verbose_name='Родительский класс')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
                'db_table': 'example_category',
            },
        ),
        migrations.DeleteModel(
            name='WarMarsh',
        ),
        migrations.AddField(
            model_name='historymarsh',
            name='category',
            field=models.ManyToManyField(to='velo.Category'),
        ),
    ]
