# Generated by Django 3.1.5 on 2021-02-03 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0008_auto_20210203_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
