# Generated by Django 3.1.5 on 2021-02-03 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0011_auto_20210203_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
