# Generated by Django 3.1.5 on 2021-02-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('velo', '0013_auto_20210203_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marsh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marsh_name', models.CharField(max_length=100)),
                ('marsh_url_1', models.URLField()),
                ('marsh_url_2', models.URLField()),
                ('marsh_text', models.TextField()),
                ('marsh_km', models.CharField(max_length=300)),
                ('marsh_time', models.CharField(max_length=30)),
                ('marsh_obj', models.CharField(max_length=300)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='velo.velomarsh', verbose_name='Категория')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoryMarsh',
        ),
    ]
