# Generated by Django 3.1.5 on 2021-02-05 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('velo', '0014_auto_20210203_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='marsh',
            name='user_mar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marsh',
            name='users_save',
            field=models.ManyToManyField(blank=True, related_name='marsh_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
