# Generated by Django 3.1.5 on 2021-01-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VeloArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_image', models.FileField(upload_to='images/')),
                ('article_text', models.TextField()),
                ('article_heading', models.CharField(max_length=300)),
                ('article_date', models.DateTimeField()),
            ],
        ),
    ]
