# Generated by Django 3.1.5 on 2021-01-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_veloarticleszagl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VeloArticlesZagl',
        ),
    ]
