# Generated by Django 3.1.5 on 2021-01-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veloobject',
            name='object_image_marsh',
            field=models.FileField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
