# Generated by Django 3.1.5 on 2021-01-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0002_veloobject_object_image_marsh'),
    ]

    operations = [
        migrations.AddField(
            model_name='veloobject',
            name='object_heading',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veloobject',
            name='object_text',
            field=models.TextField(),
        ),
    ]
