# Generated by Django 3.1.5 on 2021-01-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0003_auto_20210127_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='veloobject',
            old_name='object_image_marsh',
            new_name='object_image_map',
        ),
    ]
