# Generated by Django 3.1.5 on 2021-01-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0004_auto_20210127_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='veloobject',
            name='object_addr',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
