# Generated by Django 3.1.5 on 2021-01-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object', '0005_veloobject_object_addr'),
    ]

    operations = [
        migrations.AddField(
            model_name='veloobject',
            name='object_big_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veloobject',
            name='object_email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veloobject',
            name='object_phone',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
