# Generated by Django 3.0.6 on 2021-02-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_main_image', models.FileField(upload_to='images/')),
                ('about_main_text', models.CharField(max_length=30)),
                ('about_main_description', models.CharField(max_length=300)),
            ],
        ),
    ]
