# Generated by Django 3.0.6 on 2021-02-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_one',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_one_text', models.CharField(max_length=30)),
                ('about_one_title', models.CharField(max_length=2000)),
                ('about_one_description', models.CharField(max_length=2000)),
                ('about_one_end', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='about_main',
            name='about_main_description',
            field=models.CharField(max_length=2000),
        ),
    ]
