# Generated by Django 3.0.6 on 2021-02-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20210203_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_main',
            name='about_main_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about_one',
            name='about_one_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about_one',
            name='about_one_end',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about_one',
            name='about_one_title',
            field=models.TextField(),
        ),
    ]
