# Generated by Django 3.0.6 on 2021-02-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20210203_1120'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_partners_image', models.FileField(upload_to='images/')),
            ],
        ),
    ]
